---
title: "Codeswitching VOT - Pilot Data"
author: "Marguerite CAMERON"
date: "22 décembre 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create data frames for each participant and her VOT measurements 

These are dataframes containing the name of the participant and a small sample of the VOT measurements taken from the pilot experiment. 
VOT measurements were taken from recordings of spontaneous speech, and are of word-initial [p], [t], or [k].  There are 10 VOT samples in each category (explained below).  The words selected to comprise the data for this project are the first 10 with easy and reliable VOT measurements in the folder of audio clips from the original recording.  The 10 VOT measurements in each category are, then, quasi-random.

VOT measurements for each participant are taken first from French words in a monolingual French context and second from English codeswitch words in a predominantly French conversational context.

The first participant, F, is a native francophone bilingual in English.  Her data frame will contain two categories of VOT measurements.  The first, which will be named "L1", is of French words in a monolingual context.  The second, which will be named "L1toL2", is of English words during a predominantly French conversation.  

The second participant, P, is a native anglophone bilingual in French.  Her data frame will also contain two categories of VOT measurements.  The first, which will be named "L2", is of French words in a monolingual context.  The second, which will be named "L2toL1", is of English words during a predominantly French conversation.

The analyses that follow are intended to provide a comparison of two speakers of different native languages in their average French VOTs and their average English VOTs in instances of French to English codeswitching.
Using this sample data, predictions will be made for what to expect of more data from the same speakers or of a larger, hypothetical data set.

